#
# @file secrets.example.yaml
# @brief Example secrets file
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-01
#

wifi1_ssid: "YourWiFiSSID1"
wifi1_password: "YourWiFiPassword1"
wifi2_ssid: "YourWiFiSSID2"
wifi2_password: "YourWiFiPassword2"
api_key: "YourAPIEncryptionKey"
ota_password: "YourOTAPassword"
# Add other secrets as needed

