#
# @file basic-f785ce.yaml
# @brief Specific Configuration for a H801 device having ${full_mac} address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-03
#

substitutions:
  device_fn: "Eventail"
  device_lc: "f785ce"
  host16: 23
  room: "bureau"

packages:
  - !include models/sonoff-basic-r1.yaml            
# - !include models/sonoff-minimal.yaml            

# MAC: DC:4F:22:F7:85:CE