#
# @file basic-bc4a5d.yaml
# @brief Specific Configuration for a H801 device having ${full_mac} address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-03
#

substitutions:
    device_fn: "Right Bed Table"
    device_lc: "bc4a5d"
    ip_0: 192.168.0.21   
    room: "chambre"
    
packages:
  - !include models/sonoff-basic-r1.yaml            

#