# Specific Device Configuration

substitutions:
    device_fn: "Bridge RF433"
    device_lc: 8b60a7
    full_mac: "8b:60:a7"
    ip_0: 192.168.0.33
    room: "desk"

packages:
  - !include models/sonoff-bridge.yaml