#
# @file basic-bc4a5d.yaml
# @brief Specific Configuration for a Sonoff DUAL R3 device which MAC address ends by ${device_lc}
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-03
#

substitutions:
    device_fn: "DUAL R3 V2.0"
    device_lc: e91494
    ip_0: 192.168.0.199  
    room: "chambre"

packages:
  - !include models/sonoff-dualr3.yaml


# MAC: C8:F0:9E:E9:14:94  