#
# @file mini-tv-1.yaml
# @brief Specific Device Configuration
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_fn: "ESP32-TV (TFT)"
  device_lc: "5b6ca0"
  ip_0: 192.168.0.230
  room: salon

packages:
  - !include models/mini-tv.yaml


# Chip is ESP32-C3 (QFN32) (revision v0.4)
# Features: Wi-Fi, BT 5 (LE), Single Core, 160MHz
# Crystal is 40MHz
# MAC: b43a455b6ca0
# Manufacturer: ef
# Device: 4018
# Status value: 0x600200
# Detected flash size: 16MB - Flash Device : 16 MB - Winbond W25Q128 (128 Mbit)
# Pontage USB : Espressif Systems - ESP32 Native USB (0x1001)

# IOO - LCD_DC
# IO1 - 
# IO2 - LCD_CS
# IO3 - LCD_SCK
# IO4 - LCD_MOSI
# IO5 - LCD_RST
# IO6
# IO7
# IO8  - BUTTON TOP RIGHT
# IO9  - BUTTON BOTTOM LEFT
# IO10 - BUTTON BOTTOM RIGHT
# IO11 - RED LED
# IO
# IO18 - USB
# IO19 - USB
# IO20 - RXD
# IO21 - TXD


