#
# @file rd-1.yaml
# @brief Specific Device Configuration
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_fn: "Room Device 1"
  device_lc: "759954"
  ip_0: 192.168.0.235
  room: "chambre"

packages:
  - !include models/rd.yaml
  
# https://www.aliexpress.com/item/1005009554059578.html
# SOC: ESP32-S3 (QFN56) (revision v0.20)
# https://www.espressif.com/en/products/socs/esp32-s3
# PSRAM: 8MB (AP Memory 3.3 V)
# Flash: 16MB
# Flash ID: 0x184068
# MAX: 1c:db:d4:75:99:54
