#
# @file rd-2.yaml
# @brief Specific Device Configuration
# @author CmPi <github.com/CmPi>
#

substitutions:
    device_model: "rd"
    device_fn: "Room Device 2"
    device_lc: ""
    soc_type: "ESP32S3"
    config_version: "0.1.002"
    ip_0: 192.168.0.236
    pwr_mode: NONE
    pwr_val: 20dB
    detected_flash_size: 16MB
    room: desk
    ws2812_led_gpio: GPIO48  # used by rgb_led package

<<: !include models/rd.yaml  
