#
# @file s20-67b8ca.yaml
# @brief Specific Configuration for a Sonoff S20 device having 80:7D:3A:67:B8:CA MAC address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_fn: "Black light"
  device_lc: 67b8ca
  host16: 31
  room: "bureau"

packages:
  - !include models/sonoff-s20.yaml

# 2 stages updates:
# use sonoff-s20.mini.yaml as small initial firmware to be able to update to the full featured sonoff-s20.yaml later

# MAC: 80:7D:3A:67:B8:CA