#
# @file s20-44068f.yaml
# @brief Specific Configuration for a Sonoff S26 device having BC:DD:C2:44:06:8F MAC address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_fn: "Eggs cooker"
  device_lc: "44068f"
  host16: 36
  room: "cuisine"
    
packages:
  - !include models/sonoff-s20.yaml

# 2 stages updates:
# use sonoff-s20.mini.yaml as small initial firmware to be able to update to the full featured sonoff-s20.yaml later

# MAC: "BC:DD:C2:44:06:8F"
