# Specific Device Configuration

substitutions:
    device_fn: "Rice cooker"
    device_lc: f972a7
    config_version: "0.1.351"
    ip_0: 192.168.0.28  
    room: "cuisine"

packages:
  - !include models/sonoff-th.yaml

# MAC: "5C:CF:7F:F9:72:A7"
