#
# @file ttgo-82661-1.yaml
# @brief Specific Device Configuration
# @author CmPi <github.com/CmPi>
#

substitutions:
  device_fn: "TTGO 8266 w/ screen"
  device_lc: "91c19c"
  host16: 44
  room: "bureau"

packages:
  - !include models/ttgo8266.yaml

one_wire:
  - platform: gpio
    pin: GPIO13

sensor:
  - id: ds18b20
    platform: dallas_temp
    address: 0xc3000801e355ed10
    name: "Temperature"
    device_class: temperature    
    icon: "mdi:thermometer"
    on_value:
      if:
        condition:
          wifi.connected
        then:  
          - delay: 5s  
          - script.execute: report_ds18b20  

# Chip is ESP8266EX
# Features: Wi-Fi, 160MHz
# Crystal is 26MHz
# MAC: 68:C6:3A:91:C1:9C
# Manufacturer: c8
# Device: 4016
# Status value: 0x200002
# Detected flash size: 4MB
