#
# @file witty-1.yaml
# @brief Specific Device Configuration
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_fn: "WITTY"
  device_lc: 789bf8
  host16: 46
  room: "salon"

packages:
  - !include models/witty.yaml

# MAC: "DC:4F:22:78:9B:F8"
