#
# @file esphome.dio.yaml
# @brief Common ESPHome configuration for all devices
# @author CmPi <github.com/CmPi>
#

esphome:
  project:
    name: "CmPi.MyEhThings"
    version: $config_version
  area: "${room}"
  name: "${device_type}-${device_lc}"
  friendly_name: "$device_fn"
  platformio_options:
    board_build.ldscript: eagle.flash.1m.ld
    build_flags:
      - -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY  
      - -ffunction-sections
      - -fdata-sections
      - -Wl,--gc-sections      

esp8266:
  board: ${board}
  board_flash_mode: dout
  