substitutions:
  is_esp8266_family: "${ soc_type == 'ESP8266' or soc_type == 'ESP8285' }"

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - <<: !include ../keys/sensor.uptime.yaml
  - <<: !include ../keys/sensor.cpu_temperature.yaml
  - id: !remove ${ "cpu_temp" if is_esp8266_family else "" }
