#
# @file sonoff-dualr3.yaml
# @brief Common Configuration for Sonoff Mini-r4 devices
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-04
#

substitutions:
  device_type: "mini-r4"
  board: "esp32dev"
  soc_type: "ESP32"
  pwr_mode: LIGHT
  pwr_val: 20dB
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  detected_flash_size: 4MB
  config_version: "0.1.006"

packages:
  - !include ../packages/esphome.dio.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml
  - !include ../packages/min-info.yaml
  - !include ../packages/no-webe.yaml

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: esp-idf  
    version: recommended

# ========== BLUETOOTH PROXY ==========
#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

#bluetooth_proxy:
#  active: true    

# === SENSORS

binary_sensor:
  # Physical button on device
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    name: S2
    pin: GPIO27
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO26
    id: relay_output
  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
    id: o_led

# Relay as Switch - No restore, always starts OFF
switch:
  - platform: output
    name: "Relay"
    output: relay_output
    id: relay
    restore_mode: ALWAYS_OFF
