# === === Template for SONOFF MINIR R4

esphome:
  <<: !include .def.esphome.noboot.yaml

<<: !include .def.common.yaml

esp32:
  board: esp32dev
  variant: esp32
  framework:
    # esp-idf has Better Bluetooth performance than Arduino
    type: esp-idf  
    version: recommended

# ========== BLUETOOTH PROXY ==========
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true    

globals:
    - id: http_rsp_body
      type: std::string
      restore_value: no

# === SENSORS

binary_sensor:
  # Physical button on device
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    name: S2
    pin: GPIO27
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - switch.toggle: relay

sensor:
  - <<: !include .sensor.uptime.yaml

output:
  - platform: gpio
    pin: GPIO26
    id: relay_output
  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
    id: o_led

# Relay as Switch - No restore, always starts OFF
switch:
  - platform: output
    name: "Relay"
    output: relay_output
    id: relay
    restore_mode: ALWAYS_OFF

# Status LED as Light
light:
  - <<: !include .light.status_led.yaml

script:
    - id: declare_config
      then: 
        - !include { file: .register.component.yaml, vars: { sSensorDomain: "sensor", sSensorId: "ontime"} }  
        - delay: 10s
        - !include { file: .register.component.yaml, vars: { sSensorDomain: "sensor", sSensorId: "rssi"} }  
    - id: report_uptime
      then:
        - !include { file: .component_state.yaml, vars: { sSensorDomain: "sensor", sSensorId: "ontime"} }  
        - delay: 10s
        - !include { file: .component_state.yaml, vars: { sSensorDomain: "sensor", sSensorId: "rssi"} }  
    - id: process_json
      then:
        - delay: 1ms
      mode: single    

debug:
  update_interval: 60s

logger:
  level: INFO

mdns:
  disabled: false