#
# @file models/rd.yaml
# @brief Device configuration for "Room Device"
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_type: "rd"
  soc_type: "ESP32S3"
  config_version: "0.1.002"
  pwr_mode: NONE
  pwr_val: 20dB
  detected_flash_size: 16MB
  ws2812_led_gpio: GPIO48  # used by rgb_led package

esp32:
  board: esp32-s3-devkitm-1
  variant: $soc_type
  flash_size: ${detected_flash_size}
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM: y
      CONFIG_SPIRAM_MODE_OCT: y
      CONFIG_SPIRAM_SPEED_80M: y

psram:
  mode: octal
  speed: 80MHz

packages:
  - !include ../packages/esphome.dio.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml    
  - !include ../packages/sys-info.yaml    
  - !include ../packages/led-rgb-ws2812.yaml    
