esphome:
  name: $device_lc
  friendly_name: $device_fn
  project:
    name: "CmPi.MyEhThings"
    version: $config_version

# Wifi settings (for Prague)

wifi:
  reboot_timeout: 0s
  fast_connect: true
  min_auth_mode: WPA  
  power_save_mode: ${pwr_mode}
  output_power: ${pwr_val}
  networks:
    - ssid: !secret wifi1_ssid
      password: !secret wifi1_password
    - ssid: !secret wifi2_ssid
      password: !secret wifi2_password      
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: ${ip_0}
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0    
    dns1: 8.8.8.8        # Google DNS
    dns2: 1.1.1.1        # Cloudflare DNS 

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s  # Prevents "unavailable" status    

ota:
  - platform: esphome
    password: !secret ota_password
    
esp8266:
  board: esp01_1m
  board_flash_mode: dout

logger:
  baud_rate: 0  
  level: NONE
  
mdns:
  disabled: true