#
# @file models/sonoff-pow.yaml
# @brief common part of a TTGO
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_type: "pow"
  board: esp01_1m
  soc_type: "ESP8266"
  pwr_mode: NONE
  pwr_val: 18dB
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  status_led_gpio: GPIO15  # used by status_led package
  config_version: "0.2.002"

packages:
  - !include ../packages/esphome.esp8266.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml    
  - !include ../packages/min-info.yaml
  - !include ../packages/status_led.yaml # do not forget to define status_led_gpio in substitutions
  - !include ../packages/no-webe.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: fakebutton
  - platform: template
    name: "Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      if (isnan(id(s_power).state)) {
        return {};
      } else if (id(s_power).state > 4) {
        return true;
      } else {
        return false;
      }

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    change_mode_every: 8
    update_interval: 30s
    current:
      name: "Current"
    voltage:
      name: "Voltage"
    power:
      name: "Power"
      id: s_power
      on_value_range:
        - above: 4.0
          then:
            - light.turn_on: l_led
        - below: 3.0
          then:
            - light.turn_off: l_led
    energy:
      name: "Total Energy"
      id: total_energy_sensor
      unit_of_measurement: kWh
      accuracy_decimals: 3
      filters:
        - multiply: 0.001 # AJOUTEZ CECI POUR LE DASHBOARD ENERGY

switch:
  - platform: template
    name: "Relay"
    optimistic: true
    id: fakebutton
    restore_mode: DISABLED
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: l_led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: l_led
  - platform: gpio
    id: relay
    pin: GPIO12

#script:
#    - id: !extend declare_config
#      then: 
#        - !include { file: ../keys/script.register.component.yaml, vars: { sSensorDomain: "sensor", sSensorId: "ontime"} }  

logger:
  <<: !include ../keys/logger.error.yaml

mdns:
  disabled: true