#
# @file models/sonoff-s20.mini.yaml
# @brief Device configuration for Mini TV
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-02
#

substitutions:
  device_type: "s2x"
  board: esp01_1m
  soc_type: "ESP8266"
  ip_0: 192.168.0.${host16}   
  pwr_mode: NONE
  pwr_val: 18dB
  status_led_gpio: GPIO13  # used by status_led package
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  config_version: "0.2.8.M"

esphome:
  name: ${device_lc}
  friendly_name: "${device_fn} mini"
  platformio_options:
    board_build.ldscript: eagle.flash.1m64.ld
    build_flags:
      - -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

packages:
  - !include ../packages/esphome.esp8266.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml    

logger:
  <<: !include ../keys/logger.none.yaml
