#
# @file models/sonoff-basic-r1.yaml
# @brief Specific Configuration for a H801 device having ${full_mac} address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-03
#

substitutions:
  device_type: "basic"
  board: esp01_1m
  soc_type: "ESP8266"
  ip_0: 192.168.0.${host16}   
  pwr_mode: NONE
  pwr_val: 18dB
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  status_led_gpio: GPIO13  # used by status_led package
  config_version: "0.3.10"

packages:
  - !include ../packages/esphome.esp8266.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml    
  - !include ../packages/min-info.yaml
  - !include ../packages/status_led.yaml # do not forget to define status_led_gpio in substitutions
  - !include ../packages/webe.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    name: "Button"
    on_press:
      then:
        - switch.toggle: relay
#  - platform: gpio
#    pin:
#     number: GPIO14
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   id: button_2
#   name: "internal button"
# - platform: status
#   name: "status"
    
output:
  - id: o_relay
    platform: gpio
    pin: GPIO12
  - id: !extend o_led    
    platform: gpio
    pin:
      number: GPIO13
      inverted: true
    
# Relay switch using output
switch:
  - id: relay
    platform: output
    name: "Relay"
    output: o_relay
    on_turn_on:
      - script.execute: status_led_blinkx3
    # - script.execute: report_state
    on_turn_off:
      - script.execute: status_led_blinkx3 
    # - script.execute: report_state         

logger:
  <<: !include ../keys/logger.none.yaml
  
mdns:
  disabled: true

  