#
# @file models/sonoff-basic-r1.yaml
# @brief Specific Configuration for a H801 device having ${full_mac} address
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-03
#

substitutions:
  device_type: "basic"
  board: esp01_1m
  pwr_mode: NONE
  pwr_val: 18dB
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  config_version: "0.2.004"
  status_led_gpio: GPIO13  # used by status_led package

packages:
  - !include ../packages/esphome.esp8266.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml    
  - !include ../packages/min-info.yaml
  - !include ../packages/status_led.yaml # do not forget to define status_led_gpio in substitutions
  - !include ../packages/webe.yaml

esp8266:
  board: esp8285
  board_flash_mode: dout
  early_pin_init: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: button_1
    name: "Button"
    on_press:
      - switch.toggle: s_relay
#  - platform: gpio
#    pin:
#     number: GPIO14
#     mode:
#       input: true
#       pullup: true
#     inverted: true
#   id: button_2
#   name: "internal button"
# - platform: status
#   name: "status"

switch:
  - platform: output
    id: s_relay
    name: "Relay"
    output: o_relay

output:
  - platform: gpio
    id: o_relay
    pin: GPIO12
  - platform: gpio
    id: !extend o_led    
    pin:
      number: GPIO13
      inverted: true
    
script:
    - id: !extend declare_config
      mode: queued
      then: 
#       - !include { file: .script.register.component.yaml, vars: { sSensorDomain: "sensor", sSensorId: "ontime"} }  
        - delay: 500ms
#       - !include { file: .script.register.switch.yaml, vars: { sSensorDomain: "switch", sSensorId: "relay"} }  
        - delay: 200ms
        - script.execute: report_state   # << call it here after registration        
    - id: report_state
      mode: queued
      then:
        - delay: 500ms
#       - !include { file: .script.report.binary-switch.yaml, vars: { sSensorDomain: "switch", sSensorId: "relay"} } 

logger:
  level: ERROR
  baud_rate: 0  # disable UART logging
  
mdns:
  disabled: true

  