#
# @file sonoff-dualr3.yaml
# @brief Common Configuration for Sonoff DUAL R3 devices
# @author CmPi <github.com/CmPi>
# @date creation 2026-01-04
#

substitutions:
  device_type: "r3v2"
  board: "esp32dev"
  soc_type: "ESP32"
  pwr_mode: LIGHT
  pwr_val: 18dB
  webe_api: !secret webe_api
  webe_usrm: !secret webe_usrm    
  webe_key: !secret webe_key
  detected_flash_size: 4MB
  config_version: "0.2.006"

packages:
  - !include ../packages/esphome.dio.yaml
  - !include ../packages/wifi-mdns.yaml
  - !include ../packages/api-ota.yaml
  - !include ../packages/min-info.yaml
  - !include ../packages/no-webe.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf  
    
globals:
  - id: http_rsp_body
    type: std::string
    restore_value: no    
      
uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 4800
  parity: NONE
  stop_bits: 2

sensor:  
  - platform: bl0939
    update_interval: 30s
    voltage:
      name: 'Voltage'
    current_1:
      name: 'Current 1'
      id: 'open_current_sensor'
    current_2:
      name: 'Current 2'
      id: 'close_current_sensor'
    active_power_1:
      name: 'Active Power 1'
    active_power_2:
      name: 'Active Power 2'
    energy_1:
      name: 'Energy 1'
    energy_2:
      name: 'Energy 2'
    energy_total:
      name: 'Energy Total'

light:
  - platform: status_led
    name: "LED"
    id: led_status
    pin:
      number: GPIO13
      inverted: True
    internal: True

switch:
  - platform: gpio
    name: "1"
    pin: GPIO27
    id: relay_1

  - platform: gpio
    name: "2"
    pin: GPIO14
    id: relay_2

binary_sensor:
  - platform: gpio
    name: "Button"
    id: sensor_button
    pin:
      number: GPIO00
      mode:
        input: True
        pullup: True
      inverted: True
    disabled_by_default: True
    icon: 'mdi:radiobox-blank'
    filters:
      - delayed_on: 50ms
    on_press:
      - switch.toggle: relay_1

  - platform: gpio
    name: "1"
    pin:
      number: GPIO32
      mode:
        input: True
        pullup: True
      inverted: True
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.turn_on: relay_1
    on_release:
      - switch.turn_off: relay_1

  - platform: gpio
    name: "2"
    pin:
      number: GPIO33
      mode:
        input: True
        pullup: True
      inverted: True
    filters:
      - delayed_on_off: 50ms
    on_press:
      - switch.turn_on: relay_2
    on_release:
      - switch.turn_off: relay_2
            
logger:
  <<: !include ../keys/logger.none.yaml    
